// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoi-_CQyHhzH64rEa7GdvUDgwv5XUc6cQ',
    appId: '1:403368897446:web:8c1f42a7900ccede557d67',
    messagingSenderId: '403368897446',
    projectId: 'food-app-with-admin-pane-aa5c4',
    authDomain: 'food-app-with-admin-pane-aa5c4.firebaseapp.com',
    storageBucket: 'food-app-with-admin-pane-aa5c4.appspot.com',
    measurementId: 'G-V7MQZ98B0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBex5BspyDf51gP3joV_u3BPl6hZ1kSwBE',
    appId: '1:403368897446:android:ab0a4e924afbd8b2557d67',
    messagingSenderId: '403368897446',
    projectId: 'food-app-with-admin-pane-aa5c4',
    storageBucket: 'food-app-with-admin-pane-aa5c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQSb8lTBYv4oqgSrjNGI4naYEE2Y6lZ4',
    appId: '1:403368897446:ios:20308bdcb76ee1ba557d67',
    messagingSenderId: '403368897446',
    projectId: 'food-app-with-admin-pane-aa5c4',
    storageBucket: 'food-app-with-admin-pane-aa5c4.appspot.com',
    iosClientId: '403368897446-5so5us2fb2495ibcr0lf1nq81gmp0vp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQSb8lTBYv4oqgSrjNGI4naYEE2Y6lZ4',
    appId: '1:403368897446:ios:20308bdcb76ee1ba557d67',
    messagingSenderId: '403368897446',
    projectId: 'food-app-with-admin-pane-aa5c4',
    storageBucket: 'food-app-with-admin-pane-aa5c4.appspot.com',
    iosClientId: '403368897446-5so5us2fb2495ibcr0lf1nq81gmp0vp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoi-_CQyHhzH64rEa7GdvUDgwv5XUc6cQ',
    appId: '1:403368897446:web:390bdec1bd1e25f3557d67',
    messagingSenderId: '403368897446',
    projectId: 'food-app-with-admin-pane-aa5c4',
    authDomain: 'food-app-with-admin-pane-aa5c4.firebaseapp.com',
    storageBucket: 'food-app-with-admin-pane-aa5c4.appspot.com',
    measurementId: 'G-Z4P5PV1KLG',
  );

}